cohort_name: RA17_13
sample_names: ["RA17_13-34_1", "RA17_13-44_1", "RA17_13-50_1", "RA17_13-55_1", "RA17_13-56_1", "RA17_13-67_1", "RA17_13-73_4"]

h5s:
    RA17_13-34_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-34_1/RA17_13-34_1.mpileup.h5
    RA17_13-44_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-44_1/RA17_13-44_1.mpileup.h5
    RA17_13-50_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-50_1/RA17_13-50_1.mpileup.h5
    RA17_13-55_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-55_1/RA17_13-55_1.mpileup.h5
    RA17_13-56_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-56_1/RA17_13-56_1.mpileup.h5
    RA17_13-67_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-67_1/RA17_13-67_1.mpileup.h5
    RA17_13-73_4: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13-73_4/RA17_13-73_4.mpileup.h5

cravat_outputs:
    RA17_13-34_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-44_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-50_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-55_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-56_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-67_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt
    RA17_13-73_4: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA17_13/fillout/RA17_13_CRAVAT_output_cleaned.txt

cn_assignment_df: /home/zhangh5/work/Tapestri_batch2/analysis/falcon/RA17_13-homdel-nclones=8_solution.refined.cell_assignments.csv

snv_selection_params:
    topic: all_vars
    func_only: False
    mut_prev_threshold: [0.01]
    bq_prev_threshold: # <--- leave empty to disable
    ado_threshold: 0.3 # <--- remove SNVs that have high ADO in ANY sample
    filter_TtoC_artifact: 
        filter: True
        lower_thres: 0.005
        upper_thres: 0.01
    rescue_1000genome_af: 0.01 # rescue popular SNPs (for phylogeny purpose). disable by setting to >= 1 or None
    remove_hom_germline_snps_af:  # disable by setting to >= 1 or None
    attribute: AF_MISSING